CREATE TABLE users (
    id UUID PRIMARY KEY,
    email VARCHAR(254) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT chk_users_email_normalized CHECK (email = LOWER(BTRIM(email)))
);

CREATE UNIQUE INDEX uk_users_email_lower ON users(LOWER(email));

CREATE TABLE profiles (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    avatar_url VARCHAR(2048)
);

CREATE INDEX idx_profiles_user_id ON profiles(user_id);

CREATE TABLE subscriptions (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    plan VARCHAR(20) NOT NULL,
    started_at DATE NOT NULL,
    expires_at DATE,
    is_active BOOLEAN NOT NULL,
    CONSTRAINT chk_subscription_plan CHECK (plan IN ('BASIC', 'STANDARD', 'PREMIUM')),
    CONSTRAINT chk_subscription_dates CHECK (expires_at IS NULL OR expires_at >= started_at)
);

CREATE INDEX idx_subscriptions_user_started ON subscriptions(user_id, started_at DESC);
CREATE INDEX idx_subscriptions_active_expiry ON subscriptions(user_id, is_active, expires_at);

CREATE TABLE genres (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE movies (
    id UUID PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    thumbnail_url VARCHAR(2048),
    video_folder_url VARCHAR(128) NOT NULL UNIQUE,
    duration_seconds INTEGER NOT NULL,
    release_year INTEGER NOT NULL,
    maturity_rating VARCHAR(50),
    language VARCHAR(20),
    CONSTRAINT chk_movie_duration CHECK (duration_seconds > 0),
    CONSTRAINT chk_movie_release_year CHECK (release_year BETWEEN 1888 AND 2200),
    CONSTRAINT chk_movie_video_folder CHECK (video_folder_url ~ '^[A-Za-z0-9][A-Za-z0-9_-]{0,127}$')
);

CREATE TABLE movie_genres (
    movie_id UUID NOT NULL REFERENCES movies(id) ON DELETE CASCADE,
    genre_id INTEGER NOT NULL REFERENCES genres(id) ON DELETE CASCADE,
    PRIMARY KEY (movie_id, genre_id)
);

CREATE INDEX idx_movie_genres_genre_id ON movie_genres(genre_id);

CREATE TABLE watchlist (
    profile_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    movie_id UUID NOT NULL REFERENCES movies(id) ON DELETE CASCADE,
    added_at TIMESTAMP NOT NULL,
    PRIMARY KEY (profile_id, movie_id)
);

CREATE INDEX idx_watchlist_profile_added ON watchlist(profile_id, added_at DESC);

CREATE TABLE watch_history (
    profile_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    movie_id UUID NOT NULL REFERENCES movies(id) ON DELETE CASCADE,
    stopped_at_seconds INTEGER NOT NULL,
    watched_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (profile_id, movie_id),
    CONSTRAINT chk_watch_history_timestamp CHECK (stopped_at_seconds >= 0)
);

CREATE INDEX idx_watch_history_profile_watched ON watch_history(profile_id, watched_at DESC);
